-- Migration to add Bonds tracking
-- 20260210201000_add_bonds_table.sql

CREATE TABLE IF NOT EXISTS public.bonds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    company_name TEXT,
    isin TEXT,
    face_value NUMERIC DEFAULT 1000,
    coupon_rate NUMERIC, -- Annual percentage
    maturity_date DATE,
    quantity NUMERIC DEFAULT 0,
    avg_price NUMERIC DEFAULT 0,
    current_price NUMERIC DEFAULT 0,
    investment_amount NUMERIC DEFAULT 0,
    current_value NUMERIC DEFAULT 0,
    pnl NUMERIC DEFAULT 0,
    pnl_percentage NUMERIC DEFAULT 0,
    previous_price NUMERIC DEFAULT 0,
    yield_to_maturity NUMERIC,
    interest_frequency TEXT, -- Monthly, Quarterly, Half-Yearly, Yearly, Cumulative
    next_interest_date DATE,
    status TEXT DEFAULT 'ACTIVE', -- ACTIVE, MATURED, SOLD
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bond Transactions
CREATE TABLE IF NOT EXISTS public.bond_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    bond_id BIGINT REFERENCES public.bonds(id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL, -- BUY, SELL, MATURITY, INTEREST
    quantity NUMERIC DEFAULT 0,
    price NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    transaction_date DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    account_id BIGINT REFERENCES public.accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add bonds_enabled to app_settings
ALTER TABLE public.app_settings 
ADD COLUMN IF NOT EXISTS bonds_enabled BOOLEAN DEFAULT TRUE;

-- Enable RLS
ALTER TABLE public.bonds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bond_transactions ENABLE ROW LEVEL SECURITY;

-- Policies for bonds
CREATE POLICY "Users can view their own bonds" 
    ON public.bonds FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bonds" 
    ON public.bonds FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bonds" 
    ON public.bonds FOR UPDATE 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bonds" 
    ON public.bonds FOR DELETE 
    USING (auth.uid() = user_id);

-- Policies for bond_transactions
CREATE POLICY "Users can view their own bond transactions" 
    ON public.bond_transactions FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bond transactions" 
    ON public.bond_transactions FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bond transactions" 
    ON public.bond_transactions FOR DELETE 
    USING (auth.uid() = user_id);

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_bonds_updated_at
    BEFORE UPDATE ON public.bonds
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
