-- Migration to add Forex trading tracking
-- 20260210220000_add_forex_table.sql

-- Forex Transactions table
CREATE TABLE IF NOT EXISTS public.forex_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL, -- DEPOSIT, PROFIT, LOSS, WITHDRAWAL
    amount NUMERIC NOT NULL,
    transaction_date DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    account_id BIGINT REFERENCES public.accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add forex_enabled to app_settings
ALTER TABLE public.app_settings 
ADD COLUMN IF NOT EXISTS forex_enabled BOOLEAN DEFAULT FALSE;

-- Enable RLS
ALTER TABLE public.forex_transactions ENABLE ROW LEVEL SECURITY;

-- Policies for forex_transactions
CREATE POLICY "Users can view their own forex transactions" 
    ON public.forex_transactions FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own forex transactions" 
    ON public.forex_transactions FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own forex transactions" 
    ON public.forex_transactions FOR UPDATE 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own forex transactions" 
    ON public.forex_transactions FOR DELETE 
    USING (auth.uid() = user_id);
