
ALTER TABLE app_settings
ADD COLUMN IF NOT EXISTS stocks_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS mutual_funds_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS fno_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS ledger_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS income_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS expenses_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS goals_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS family_visible BOOLEAN DEFAULT TRUE;
